name: Build App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: |
        chmod +x Resources/Scripts/compile.release.mobile.ci.sh
        ./Resources/Scripts/compile.release.mobile.ci.sh "$(pwd)" "$(pwd)/Asspp.tipa"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Asspp.tipa
        path: Asspp.tipa
        
